# Generated by Django 5.1.1 on 2024-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0002_formfield_fieldoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
