# Generated by Django 5.1.1 on 2024-10-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0003_formfield_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="form_hash",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
