# Generated by Django 5.1.1 on 2024-10-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0004_form_form_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="form_hash",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
