# Generated by Django 5.1.1 on 2024-10-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0006_alter_formfield_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Field"),
                    ("textarea", "Text Area"),
                    ("radio", "Radio Buttons"),
                    ("checkbox", "Checkbox"),
                    ("select", "Dropdown"),
                    ("date", "Date Picker"),
                    ("email", "Email Field"),
                ],
                max_length=50,
            ),
        ),
    ]
